import type { StylistSelections } from "./closai/types";
import looksJson from "@/data/looks.json";

/** Outfits chosen by the stylist model, generated by `npm run select` and committed. */
export const stylistSelections = looksJson as StylistSelections;
